services:
  # ==================== QA ====================
  mysql-qa:
    image: mysql:8.0
    container_name: DB_QA
    restart: always
    env_file:
      - ./qa/.env.qa
    ports:
      - "3308:3306"
    networks:
      - network_qa
    volumes:
      - mysql_data_qa:/var/lib/mysql
      - "./backups/qa:/backups/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    labels:
      - com.sgh.group=sgh
      - com.sgh.environment=qa

# ==================== VOLÃšMENES ====================
volumes:
  mysql_data_qa:
    driver: local
    name: mysql_data_qa

# ==================== REDES ====================
networks:
  network_qa:
    driver: bridge