version: '3.8'

services:
  # ==================== STAGING ====================
  postgres-staging:
    container_name: DB_Staging
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./staging/.env.staging
    ports:
      - "5434:5432"
    networks:
      - network_staging
    volumes:
      - postgres_data_staging:/var/lib/postgresql
      - "./backups/staging:/backups/postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - com.sgh.group=sgh
      - com.sgh.environment=staging

# ==================== VOLÃšMENES ====================
volumes:
  postgres_data_staging:
    driver: local
    name: postgres_data_staging

# ==================== REDES ====================
networks:
  network_staging:
    driver: bridge
    name: network_staging
    external: true