version: '3.8'

services:
  # ==================== PRODUCCIÓN ====================
  mysql-prod:
    image: mysql:8.0
    container_name: DB_Prod
    restart: always
    env_file:
      - ./prod/.env.prod
    ports:
      - "3310:3306"
    networks:
      - network_prod
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - "./backups/prod:/backups/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    labels:
      - com.sgh.group=sgh
      - com.sgh.environment=prod

# ==================== VOLÚMENES ====================
volumes:
  postgres_data_develop:
    driver: local
    name: postgres_data_develop
  postgres_data_qa:
    driver: local
    name: postgres_data_qa
  postgres_data_staging:
    driver: local
    name: postgres_data_staging
  mysql_data_prod:
    driver: local
    name: mysql_data_prod

# ==================== REDES ====================
networks:
  network_develop:
    driver: bridge
    name: network_develop
  network_qa:
    driver: bridge
    name: network_qa
  network_staging:
    driver: bridge
    name: network_staging
  network_prod:
    driver: bridge
    name: network_prod