version: '3.8'

services:
  # ==================== PRODUCCIÃ“N ====================
  sgh-api-prod:
    container_name: API_Prod
    image: sgh-api-prod:latest
    restart: always
    env_file:
      - ./prod/.env.prod
    ports:
      - "8085:8085"
    networks:
      - network_prod
    external_links:
      - DB_Prod:postgres-prod
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8085/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    labels:
      - com.sgh.group=sgh
      - com.sgh.environment=prod

# ==================== REDES ====================
networks:
  network_develop:
    driver: bridge
    name: network_develop
    external: true
  network_qa:
    driver: bridge
    name: network_qa
    external: true
  network_staging:
    driver: bridge
    name: network_staging
    external: true
  network_prod:
    driver: bridge
    name: network_prod
    external: true