services:
  # ==================== STAGING ====================
  mysql-staging:
    image: mysql:8.0
    container_name: DB_Staging
    restart: always
    env_file:
      - ./staging/.env.staging
    ports:
      - "3309:3306"
    networks:
      - network_staging
    volumes:
      - mysql_data_staging:/var/lib/mysql
      - "./backups/staging:/backups/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    labels:
      - com.sgh.group=sgh
      - com.sgh.environment=staging

# ==================== VOLÃšMENES ====================
volumes:
  mysql_data_develop:
    driver: local
    name: mysql_data_develop
  mysql_data_qa:
    driver: local
    name: mysql_data_qa
  mysql_data_staging:
    driver: local
    name: mysql_data_staging
  postgres_data_prod:
    driver: local
    name: postgres_data_prod

# ==================== REDES ====================
networks:
  network_develop:
    driver: bridge
  network_qa:
    driver: bridge
  network_staging:
    driver: bridge
  network_prod:
    driver: bridge